### ISSUE TITLE
Hello World Data

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#103]
Hello, Assuming a user starting with a blank DB, there should be a way to push some initial values as:

- Site Title.
- Site Description.
- A "Hello World" post.
- An example media image.

I would imagine a frontend script or similar is checking (if db is empty) once a user successfully logged in into the admin area and push those in background into the DB.

**Comment by Abdelaziz18003** [comment]
@mahnouman @gresalahi I will start working on this issue

**Comment by mahnouman** [comment]
Hello, We can do this feature on a new menu page called "Database", so I imagine there will be a button or so when the user clicks on it, it will populate the DB with the demo data. Something like that. But since this is a dangerous option if the DB allready contains something we need to put a strong confirmation method.

**Comment by coderpradp** [comment]
@mahnouman Feature is added in a585cc345b5068ae57e2319b900d1d86d927e8f2 and some issues were fixed by me in fb901469704bb6af236e5cf7fa6ce3d3ac673d06
Issue can be closed now
