### ISSUE TITLE
Website logo

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#105]
Ability to upload/modify website logo from the admin settings page. The logo should be visible in this section after it is being uploaded:
![image](https://user-images.githubusercontent.com/5932628/35983886-885444fe-0d0c-11e8-8d5c-29909be5784f.png)

**Comment by mornir** [comment]
I think it would nice to accept here a string + an small image. I can work on it this weekend. 😃

**Comment by mahnouman** [comment]
Hi Jerome, thank you , that would be great. Yes the setup of logo , logo+slogan or just slogan is possible, if it won't complicate things. Thanks alot for your support

**Comment by mahnouman** [comment]
Hi ,
Mornir submitted before a related pull request:
https://github.com/tamiat/tamiat/pull/112

It was just wrong from the targeted branch, but the code there still very helpful

**Comment by mornir** [comment]
@Pajicc Yes, you can take care of this issue and reuse some of my code.
I wanted to resubmit it last weekend, but I had trouble making ESlint work with Prettier :stuck_out_tongue_closed_eyes: I think I'm just gonna disable Prettier.

I moved this.displaySettings() function from the updated hook into the created hook, but I later understood why it was in there in the first place. But I still think that the current implementation looks a bit hacky with incrementing updatesCounter.

And what do you think about the idea of having a new Firebase reference for default settings (settings than can't be deleted)?

**Comment by Pajicc** [comment]
@mornir Hello, I finished this topic but i didn't need to use your code :D Yea i think also that incrementing counter is not the best solution... I can get into it a little bit and try to think of better solution.
Yes that's good idea, this could be implemented with the current issue #103

**Comment by gresalahi** [comment]
https://github.com/tamiat/tamiat/pull/125
