### ISSUE TITLE
blank welcome admin page

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#114]
When logged in into the admin area, the page displays a b;lank frame:
![image](https://user-images.githubusercontent.com/5932628/36077614-89d55a94-0f86-11e8-9f75-1d62d9d1f687.png)

We need to provide a welcome page here instead of the blank frame. It should contain something like welcome to Tamiat CMS, our logo maybe, a link to the repo, version information if we save this somewhere.

Let us have a simple welcome page then we take it from there.

Thank you

**Comment by Pajicc** [comment]
Will this be ok?
![image](https://user-images.githubusercontent.com/18647471/36105267-71a0229a-1014-11e8-960a-0f8d8feba37b.png)

**Comment by mahnouman** [comment]
Yes, this will do the job for now. Thanks
