### ISSUE TITLE
Posts tags shape

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#121]
The way we enter tags at the moment is quite basic from the appearance point of view. They should look like:
![image](https://user-images.githubusercontent.com/5932628/36322762-f482c45a-1367-11e8-9d8d-c44b5f1637a0.png)

**Comment by michu1234** [comment]
In progress...

**Comment by michu1234** [comment]
@mahnouman please look at [https://github.com/michu1234/tamiat/blob/develop/src/components/Admin/content/PostNew.vue](url)

I've reworked tags box

**Comment by mahnouman** [comment]
Hello,
I got this
c:\tamiat\tamiat>npm run dev

> tamiat@1.0.0 dev c:\tamiat\tamiat
> webpack-dev-server --inline --progress --config build/webpack.dev.conf.js

 94% asset optimization

 ERROR  Failed to compile with 1 errors                                                                       7:03:46 PM


 error  in ./src/components/Admin/content/PostNew.vue


  ✘  http://eslint.org/docs/rules/indent                   Expected indentation of 6 spaces but found 12
  src\components\Admin\content\PostNew.vue:153:1
              if(this.inputData !== ""){
   ^

  ✘  http://eslint.org/docs/rules/keyword-spacing          Expected space(s) after "if"
  src\components\Admin\content\PostNew.vue:153:13
              if(this.inputData !== ""){
               ^

  ✘  http://eslint.org/docs/rules/quotes                   Strings must use singlequote
  src\components\Admin\content\PostNew.vue:153:35
              if(this.inputData !== ""){
                                     ^

  ✘  http://eslint.org/docs/rules/space-before-blocks      Missing space before opening brace
  src\components\Admin\content\PostNew.vue:153:38
              if(this.inputData !== ""){
                                        ^

  ✘  http://eslint.org/docs/rules/indent                   Expected indentation of 8 spaces but found 12
  src\components\Admin\content\PostNew.vue:154:1
              this.tags.push(`${this.inputData} ×`);
   ^

  ✘  http://eslint.org/docs/rules/semi                     Extra semicolon
  src\components\Admin\content\PostNew.vue:154:50
              this.tags.push(`${this.inputData} ×`);
                                                    ^

  ✘  http://eslint.org/docs/rules/indent                   Expected indentation of 8 spaces but found 12
  src\components\Admin\content\PostNew.vue:155:1
              this.inputData = '';
   ^

  ✘  http://eslint.org/docs/rules/semi                     Extra semicolon
  src\components\Admin\content\PostNew.vue:155:32
              this.inputData = '';
                                  ^

  ✘  http://eslint.org/docs/rules/indent                   Expected indentation of 6 spaces but found 12
  src\components\Admin\content\PostNew.vue:156:1
              }
   ^

  ✘  http://eslint.org/docs/rules/indent                   Expected indentation of 6 spaces but found 12
  src\components\Admin\content\PostNew.vue:159:1
              this.tags.splice(index, 1);
   ^

  ✘  http://eslint.org/docs/rules/semi                     Extra semicolon
  src\components\Admin\content\PostNew.vue:159:39
              this.tags.splice(index, 1);
                                         ^

  ✘  http://eslint.org/docs/rules/no-multiple-empty-lines  Too many blank lines at the end of file. Max of 0 allowed
  src\components\Admin\content\PostNew.vue:177:1

   ^


✘ 12 problems (12 errors, 0 warnings)


Errors:
  5  http://eslint.org/docs/rules/indent
  3  http://eslint.org/docs/rules/semi
  1  http://eslint.org/docs/rules/no-multiple-empty-lines
  1  http://eslint.org/docs/rules/space-before-blocks
  1  http://eslint.org/docs/rules/quotes
  1  http://eslint.org/docs/rules/keyword-spacing

 @ ./src/router/index.js 11:0-58
 @ ./src/main.js
 @ multi (webpack)-dev-server/client?http://localhost:8080 webpack/hot/dev-server ./src/main.js

**Comment by michu1234** [comment]
@mahnouman  please check this once again. I've removed all bugs.

**Comment by mahnouman** [comment]
Hello, thank you, now it compiles, but some issues:
1) The new tags are only visible when creating a new post, if I re-edit the post or display it in the all view, I still see the ugly comma separated ones
![image](https://user-images.githubusercontent.com/5932628/36467922-7eb53b68-16fa-11e8-8355-f2a7ae8d9f07.png)

2) We need to make sure that any leading or trailing whitespaces are automatically removed, so 
" example" or "example " or " example " , should all have their white spaces removed and saved as "example" BUT "This Is An Example" should be left the same , since those are white spaces in the middle.

Then please create a pull request.
Thanks
