### ISSUE TITLE
Routing from DB

### ISSUE THREAD

**Issue by mahnouman** [tamiat/tamiat#138]
We would like to add Routing feature to replace the pages menu, in this routing feature the user should be able to create client side routes, by applying a specific content (Currently post) Or NULL to a specific template and hence creating a route.
These routing information should be stored in the DB.
We should evaluate these routes after the hardcoded ones which are shipped with the CMS. For example if the user created a /admin route it should has no effect on us, since /admin/* is a hardcoded route.

**Comment by Abdelaziz18003** [comment]
Hi @mahnouman I started working on this issue and I need some clarifications about it .. now I am hardcoding some "dynamic" routes assuming that I am getting them from the database.

the routes are like that: 
```
let dynamicRoutes = [
  {
    path: '/dynamic1', // the dynamic route
    component: 'Admin' // the template name .. it points to Admin.vue file for example
  },
  {
    path: '/dynamic2',
    component: 'Login'
  }
]
```

1. So now .. how do we store these routes on the database? do we store them in a separate collection called routes ?

2. We may need to create a template folder inside the `app`, so we will know where to look for dynamic templates files after getting their names from the db. What do you think ?

**Comment by mahnouman** [comment]
Hello. I do not understand the question. What would be stored in the db is enough information to locate the vue template. Path or something
