### ISSUE TITLE
Make hardcoded routes visible in the screen

### ISSUE THREAD

**Issue by pravosudova** [tamiat/tamiat#157]
Please change to make hardcoded routes visible. For now they they are not visible for user
We need to tell the user that we are already using /admin /login or whatever, so we need to display them, he might not be able to edit them, it might be just a note that Preserved routes are:
/
/admin
/login
And whatever we already using.

**Comment by coderpradp** [comment]
As of now, users get error notification if they try to create a new route same as existing and hard coded route. So, the issue seems to be fixed.
