### ISSUE TITLE
Templates are broken -replace with working

### ISSUE THREAD

**Issue by pravosudova** [tamiat/tamiat#160]
Please replace  provided template 1 and template2 which are broken templates,  with another two templates with meaningful names whom should be actually doing something, like this:
File name: blogpost.vue , Display name: “Blog Post” , takes a content of type post as input and displays it.
File name: aboutus.vue , Display name: “About Us” , takes no content and displays an About Us page with pseudo test.
Those templates “Must” inherit the app style, (inherit does not mean copying the styles of the app in each template file).
Thank you

**Comment by coderpradp** [comment]
Fixed
