### ISSUE TITLE
Need to fix styles in home page according to exmaple

### ISSUE THREAD

**Issue by pravosudova** [tamiat/tamiat#169]
For now we have problems in home page styles Some stuff in the homepage is broken, content, styles, javascript. 
So lets do homepage  perfectly clean and represent the options and features of the CMS.
Like refference: https://tutorialzine.com/2016/06/freebie-landing-page-template-with-flexbox

Thank you :)

**Comment by coderpradp** [comment]
@mahnouman Seems to be fixed and working as expected.
