### ISSUE TITLE
image insert in text editor - Uncaught (in promise) TypeError: Cannot read property 'insertImage' of undefined

### ISSUE THREAD

**Issue by Bfaycal** [tamiat/tamiat#173]
trying to insert an image in the text editor i get this message in the console :

Uncaught (in promise) TypeError: Cannot read property 'insertImage' of undefined
    at eval (image-loader.js?80c8:20)

**Comment by ahmadzein** [comment]
same here !

**Comment by mahnouman** [comment]
Hello, we are changing the way data is inserted into the DB in the next release v0.3.0, will consider this issue for that release.

**Comment by coderpradp** [comment]
@mahnouman already fixed in aa7a00caae78bbf1ca4fcae34a8f3506973074d5 Safe to close it
