### ISSUE TITLE
Adjust front page according to design

### ISSUE THREAD

**Issue by pravosudova** [tamiat/tamiat#180]
Hello, please adjust the front page according to design  which is shared in zip website-specs-tamiat
Thank you

**Comment by pravosudova** [comment]
@nikkanetiya adjust the homepage to make it example of the features we haveThis means it will not have static content, but rather use the information from the CMSso converting the static content their in the homepage into content from the CMS
there is a section of the work examplesbut should be reading from the CMS not static contentWhat others Say section, should also be from the CMSblog sectionand so on 
If something not clear you can always ask 
Thank you

**Comment by coderpradp** [comment]
@mahnouman Safe to close it.
