### ISSUE TITLE
Screen shots for the readme.md file

### ISSUE THREAD

**Issue by Abdelaziz18003** [tamiat/tamiat#189]
This is not an issue .. it is just a place where we can upload images for the readme file

**Comment by Abdelaziz18003** [comment]
![screenshot-2018-5-10 tamiat cms front end focused cms based on vue js and firebase](https://user-images.githubusercontent.com/11301627/39885992-0a34d1c6-5486-11e8-80a9-8742ac7db9d4.png)

**Comment by coderpradp** [comment]
@mahnouman I guess this should be closed since it is not an issue. We can manage a different imgur album for screenshots.
