### ISSUE TITLE
Docs?

### ISSUE THREAD

**Issue by corysimmons** [tamiat/tamiat#2]

**Comment by mahnouman** [comment]
Hi Cory, Docs would be ready next, in a week or so. Thanks for being an early adopter :)

**Comment by mahnouman** [comment]
Hi Cory, please check the current Read Me version. It was updated with some instructions.
https://github.com/tamiat/tamiat/blob/master/README.md

Let us know if something is missing that you would be looking for.

**Comment by corysimmons** [comment]
Would love to see some screenshots. :)

**Comment by NickolasBoyer** [comment]
@corysimmons these were just added in 14a630064cd33bfc60971d1177c4d66074df9ace

**Comment by corysimmons** [comment]
Neat, thank you!
