### ISSUE TITLE
Fields will be not generated while selecting content type from Edit content type

### ISSUE THREAD

**Issue by nikkanetiya** [tamiat/tamiat#203]
## How to open an Issue?
Go to admin panel /admin/content. Just select any content type from Edit content type. The selected fields will be checked in Available fields checkboxes, but we will not get any fields below `Fields`.
 
  ### Description
  - This will cause an issue when we want to edit sortable or sequence for fields.

**Comment by coderpradp** [comment]
@mahnouman This issue was already fixed in commit d0b188ad27897bd5bcf6fbe534347069f790e9d5 So, it can be closed.
