### ISSUE TITLE
Update Content Type will not update fields visiblity

### ISSUE THREAD

**Issue by nikkanetiya** [tamiat/tamiat#206]
In `admin/content` on select any content type under the Fields, we are showing all fields which each textbox type field we have a checkbox to select whether to show that field in a list or not? It will work fine when we create new Content Type But it will not work while editing.

**Comment by coderpradp** [comment]
@mahnouman This issue was already fixed in commit d64519b9dcb05cf63fce91043f09f82f64c1c1e8 So it can be closed now
