### ISSUE TITLE
This relative module was not found (Posts)

### ISSUE THREAD

**Issue by Bulletninja** [tamiat/tamiat#23]
I follow the instructions and i can't get it to compile, i always get this error:

>  ERROR  Failed to compile with 1 errors                                                                                                                                                                     14:51:34
> 
> This relative module was not found:
> 
> * ../components/content/Posts in ./src/router/index.js
>

**Comment by Bulletninja** [comment]
Fixed it renaming the "posts.vue" file in "./components/content/" to "**P**osts.vue"

**Comment by mahnouman** [comment]
Hi, thanks for highlighting this, would include the fix in the upcoming release. How is your testing so far? If there are specific issues or features you would like to see implemented please open issues for them. Thank you
