### ISSUE TITLE
Missing dependancy - moment

### ISSUE THREAD

**Issue by kieranwild** [tamiat/tamiat#33]
Was getting the following error:

**This dependency was not found:
moment in ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/components/content/Posts.vue
To install it, you can run: npm install --save moment**

To fix it add this to dependancies list in package.json 
    "moment": "^2.18.1"

**Comment by NickolasBoyer** [comment]
This should be fixed now, a little mistake I made when merging, my apologies for the inconvenience.
