### ISSUE TITLE
Posts tab - first letter

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#61]
posts tab - first letter toUpperCase()  // maybe we can use filter for that

![posts](https://user-images.githubusercontent.com/24733645/34733054-599c2080-f567-11e7-919e-dc0a5a662556.PNG)

**Comment by mrbatocko** [comment]
Sidebar navigation is now using vuetify's components, so it's fixed now.

**Comment by gresalahi** [comment]
@mrbatocko Thank you for the update.
