### ISSUE TITLE
Admin top bar issues

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#63]
# logo dissappear on wide screen

![logo](https://user-images.githubusercontent.com/24733645/34733295-234a2b66-f568-11e7-8931-8cf5e0370066.PNG)

# fix mobile version of top bar:
 - push e-mail address and log out button to right?
 - activate on smaller screen only

![top bar](https://user-images.githubusercontent.com/24733645/34733312-2e494f10-f568-11e7-85f1-18d796b6076d.PNG)

**Comment by coderpradp** [comment]
@mahnouman It is already fixed
