### ISSUE TITLE
New post creation

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#65]
#### user can not add new post until at least one tag was added; maybe we should add some validation / tooltip to inform about it

![post valid](https://user-images.githubusercontent.com/24733645/34734635-b68b9b86-f56c-11e7-8a9b-18c3256467d9.PNG)

**Comment by mahnouman** [comment]
Tags should not be mandatory

**Comment by Abdelaziz18003** [comment]
@mahnouman maybe this issue should be closed if the problem is solved
