### ISSUE TITLE
Image and firebase

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#66]
#### images aren't available in firebase after saving post

![img](https://user-images.githubusercontent.com/24733645/34735080-6404ded4-f56e-11e7-8350-9f64704cff3f.PNG)

**Comment by Pajicc** [comment]
![image](https://user-images.githubusercontent.com/18647471/36103227-0a45181c-100f-11e8-8433-169f5c4aafc9.png)
Can you check again please, cause for me it works?
Try entering into firebase console -> then into storage, you initialize it that way

**Comment by michu1234** [comment]
Everything is OK now.

**Comment by mahnouman** [comment]
Closing this, thanks for helping
