### ISSUE TITLE
Nav menu builder

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#70]
#### we need to create navigation builder and add it e.g. to settings tab
- user should be able to build menu with pages / post titles / post categories / or his own links

**Comment by mahnouman** [comment]
Hello, It is a good start, but let us have the basic functionality out of this. Add, delete, reorder and multi-layer.
This path should be a route alias. So for example we create a page called Contacts, then refer to it when building the navigation. The path can be also something the user type manually like external link or html anchor.
Thanks

**Comment by Abdelaziz18003** [comment]
@mahnouman I think this issue might be closed now
