### ISSUE TITLE
Propositions of improvements in 'posts' tab

### ISSUE THREAD

**Issue by michu1234** [tamiat/tamiat#72]
#### These are some propositions of improvements for Tamiat according to Wordpress features:

* add posts categories in order to improve silo structure (for SEO)
![add posts categories in order to improve silo seo](https://user-images.githubusercontent.com/24733645/35174344-561c526c-fd6f-11e7-9acf-b4fcfbfa37de.PNG)
* add filtering (published, saved, all) and bulk actions (especially bulk delete)
![filtering and bulk actions published and saved](https://user-images.githubusercontent.com/24733645/35174426-af9e347c-fd6f-11e7-96de-857a6568438a.PNG)
* searching post by title
![searching post by title](https://user-images.githubusercontent.com/24733645/35174452-c975e0b6-fd6f-11e7-99b6-c9a4aec35e2e.PNG)
* sorting
![sort](https://user-images.githubusercontent.com/24733645/35174479-e43fe2d4-fd6f-11e7-92d0-a446ea3fb119.PNG)
* edit categories and tags inside menu (under post tab)
![edit categories and tags in side menu](https://user-images.githubusercontent.com/24733645/35174522-0229acb2-fd70-11e7-92fc-7ed67636f4f2.PNG)
* confusing button values (add new && add)
![confusing button values](https://user-images.githubusercontent.com/24733645/35174605-4103dfd4-fd70-11e7-952a-466c7eb540cf.PNG)
* maybe instead 'add' we can choose 'publish' and 'save draft'
![publish or only save draft](https://user-images.githubusercontent.com/24733645/35174621-4abc99da-fd70-11e7-86d7-bd55fe93dcc8.PNG)
* maybe better would be 'featured image' instead
![featured image or multimedia to post](https://user-images.githubusercontent.com/24733645/35174656-70594648-fd70-11e7-9c29-48f49e8aedb3.PNG)

**Comment by Pajicc** [comment]
![image](https://user-images.githubusercontent.com/18647471/36174491-c4963464-110c-11e8-8acd-fb6b0f1f5c93.png)
Does this search by title and sorting look okay?
1. Do we have some ideas on what categories should we have, do we let users input it as a new property in post?
2. For filtering we can maybe add a new property 'state' which can be published or saved?
3. Any suggestions on what to define as bulking actions? Maybe add a select box before post so the actions can be - select all, delete selected, etc?

**Comment by mahnouman** [comment]
Hello,
1) User should input it, usually we should be shiopping the hello world post with an example category.
2) Yes, publishing state is a good idea.
3) We can have the bulk action with delete only for now. and the method of markign as you said, select all, deselect all or manually check each post.

Generally speaking if in doubt, it would be a good idea to check how it is implemented in worpdress or ghost cms.

**Comment by gresalahi** [comment]
https://github.com/tamiat/tamiat/pull/125
https://github.com/tamiat/tamiat/pull/123
https://github.com/tamiat/tamiat/pull/120
