### ISSUE TITLE
New Post wysiwyg [bug]

### ISSUE THREAD

**Issue by dan-leech** [tamiat/tamiat#94]
Wysiwyg has broken representation on Chrome 50.0.2661.102 (64-bit)
![screencapture-localhost-8081-admin-posts-new-1517078312903](https://user-images.githubusercontent.com/6331634/35475200-6010658c-03ab-11e8-913f-3653a17f1883.png)

**Comment by gresalahi** [comment]
This issue is related to #92

**Comment by Abdelaziz18003** [comment]
@gresalahi I created a pull request with a fix. @dan-leech thanks for opening this issue :)

**Comment by mahnouman** [comment]
Hello, is this issue fixed? Checking if we can close it.

**Comment by mahnouman** [comment]
Closing for comment on duplicate issue #92
