### ISSUE TITLE
[Question] Contributing

### ISSUE THREAD

**Issue by mornir** [tamiat/tamiat#97]
Hi!

I want to edit the files in my code editor and then submit pull requests, but I have some problems setting up the git workflow.
So far I did:

1. Fork the repo
1. Clone the forked repo to my local computer
1. Checkout the feature/refactor branch (I'm mainly interested in contributing to the Vuetify refactor)
1. Edit the necessary files to make it work on my side (config.js, database.rules.json, etc.)
1. Work on the project
1. Push my changes to the forked repo
1. Submit a pull request

Everything is fine, but how can I ignore files so they don't appear in my pull request? For example, the config.js file contains my Firebase config and should not part of pull requests.

It is the first time that I contribute to a repo without making changes directly on GitHub 😊

**Comment by Abdelaziz18003** [comment]
Hi @mornir, we really appreciate your contribution to the project and we are happy to give help :)

1. make your changes on a file (ex: index.html).
2. after that, you will have two modified files or more (index.html, config.js, .. etc).
3. before making a commit, add only the file that you want to check (home.vue in this case) with this command `git add index.html` .. if you have more files you can chain them like so `git add file1.js file2.js file3.js`
4. make a commit with `git commit -m "your commit message"`.
5. push changes to the forked repo.
6. make a pull request.
7. enjoy merging the pull request.
8. Thanks for contributing

**Comment by Abdelaziz18003** [comment]
please feel free to ask if something doesn't make sense for you :)

**Comment by mornir** [comment]
Awesome, it works! 👍 
Actually my problem came from a setting enabled in vs code "git.enableSmartCommit", which automatically commit everything if there are no staged changes. Now I just need to right-click individual files in the source control panel in order to stage them.
