### ISSUE TITLE
[Question] Style Guide

### ISSUE THREAD

**Issue by mornir** [tamiat/tamiat#98]
Is there a style guide to follow? For example should I use semicolons, single quotation mark, etc?
I had a look at the code and the style is not always consistent.

**Comment by Abdelaziz18003** [comment]
This is interesting .. maybe we have to setup a code linter (eslint) so all the contributors will be using the same code style. @mahnouman what do you think ?

**Comment by mornir** [comment]
What I did is create a .prettierrc file at the root of the project, which overrides my global settings for Prettier. It works well this way and the code is prettified upon saving.

**Comment by Abdelaziz18003** [comment]
Hi @mornir .. Prettier is a code formatter .. But as I know the majority of javascript and vue.js community use eslint for style guides .. Moreover it is used by the Vue CLI out of the box when starting a new project .. I think it would be the right choice for us as long as we are using Vue.js .. but anyway you can live with both eslint and prettier by giving it the same configs as eslint rules. It would be a good idea to avoid headache and not let a chance for Eslint it to complain about your code :)

**Comment by Abdelaziz18003** [comment]
I will work on this issue

**Comment by mornir** [comment]
Yes, having Prettier auto-format before linting is the best way. I hate when ESLint prevents my app from starting because I forgot a semicolon :confounded:

**Comment by Abdelaziz18003** [comment]
@mornir so it is up to @mahnouman to decide .. do we need to add eslint or not

**Comment by mahnouman** [comment]
Hello, Yeah, let us do what people working on Vue code are doing. It is not clear for me what exactly needed to be done, but for example when I enable eslint with our project it complains a lot.  I vote for Prettier + eslint.
Any clue what changes are needed to have this setup?
Thank you

**Comment by mornir** [comment]
Who is in favor of using semicolons? (react with thumb up or thumb down)

**Comment by mornir** [comment]
Who is in favor of using single quotation marks? (react with thumb up or thumb down)

**Comment by mornir** [comment]
Who is in favor of using trailing commas where valid in ES5 (objects, arrays, etc.)? (react with thumb up or thumb down)

**Comment by mornir** [comment]
@Abdelaziz18003 I hope this quick survey helps you configure Prettier/ESlint 😉

**Comment by mahnouman** [comment]
I prefer just following vuejs guidelines for their own development.

**Comment by Abdelaziz18003** [comment]
@mahnouman the eslint configuration now is the vue.js standard config .. so if it is Ok this issue might be closed
